"""Write machine-readable JSON and human-readable Markdown outputs from the run."""
from __future__ import annotations

import json
import os

import pandas as pd

from . import io_utils

# Readable label per family code (config carries the code on each method).
FAMILY_LABEL = {
    "no_handling": "no handling",
    "removal_distribution": "removal / trimming",
    "removal_business": "removal (business rule)",
    "capping_business": "capping (business rule)",
    "capping_distribution": "capping (distribution)",
    "winsorization": "winsorization",
}


def _family_map(config):
    """method name -> readable family label, derived from the config method menu."""
    return {m["name"]: FAMILY_LABEL.get(m["family"], m["family"]) for m in config["methods"]}


def _fmt(x, p=4):
    try:
        return f"{x:.{p}f}"
    except (TypeError, ValueError):
        return str(x)


def _summary_table_md(summary: pd.DataFrame, metric: str, order, fam) -> str:
    g = summary[summary["metric"] == metric].set_index("method").reindex(order).reset_index()
    lines = [
        "| method | family | early->long R2 | pred RMSE | early CI covers eventual | valid | predictiveness | RMSE vs truth (validation) | bias (validation) |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for _, r in g.iterrows():
        valid = "yes" if bool(r.get("eligible", True)) else "NO (early CI misses)"
        lines.append(
            f"| {r['method']} | {fam.get(r['method'],'')} | "
            f"{_fmt(r['pred_r2'],3)} | {_fmt(r['pred_rmse'])} | {_fmt(r['early_cover_long'],3)} | "
            f"{valid} | {_fmt(r['composite_score'],3)} | {_fmt(r['rmse_truth'])} | {_fmt(r['bias'])} |"
        )
    return "\n".join(lines)


def write_all(config, summary, winners, per_exp, dec, impact, image_paths):
    io_utils.ensure_dirs()
    order = [m["name"] for m in config["methods"]]
    fam = _family_map(config)
    metrics = config["metrics"]

    # JSON: full results.
    io_utils.write_json(os.path.join(io_utils.OUTPUTS_DIR, "framework_results.json"), {
        "config_seed": config["master_seed"],
        "winners": winners,
        "summary": summary.to_dict(orient="records"),
    })
    io_utils.write_json(os.path.join(io_utils.OUTPUTS_DIR, "decision_impact.json"), {
        "decision_table": dec.to_dict(orient="records"),
        "business_impact": impact,
    })

    # Markdown: per-metric results.
    md = ["# Per-metric method comparison",
          "",
          "Generated by scripts/run_demo.py from the fixed-seed synthetic bank. "
          "All numbers are from the actual run. Relative treatment effects are in "
          "proportion units (0.02 = a 2 percent change).",
          ""]
    for i, (metric_name, mcfg) in enumerate(metrics.items(), start=1):
        w = winners[metric_name]
        md += [
            f"## {i}. {mcfg['label']}",
            "",
            f"Family: {mcfg['family']}. Expected winner (design intent): "
            f"`{mcfg['expected_winner']}`. Selected winner (from the run): "
            f"**`{w['method']}`**.",
            "",
            f"Outlier story: {mcfg['outlier_story']}",
            "",
            _summary_table_md(summary, metric_name, order, fam),
            "",
            f"Winner `{w['method']}`: early->long R2 {_fmt(w['pred_r2'],3)}, pred RMSE "
            f"{_fmt(w['pred_rmse'])}, early CI covers the eventual estimate "
            f"{_fmt(w['early_cover_long'],3)} of the time (predictiveness score "
            f"{_fmt(w['composite_score'],3)}). Validation against the known truth: bias "
            f"{_fmt(w['bias'])}, RMSE {_fmt(w['rmse_truth'])}, CI coverage {_fmt(w['ci_coverage'],3)}.",
            "",
            (f"Disqualified by the calibration gate (early CI covers the eventual estimate below "
             f"{config['scoring']['calibration_gate']}): "
             f"{', '.join('`'+m+'`' for m in w['disqualified_by_gate']) if w['disqualified_by_gate'] else 'none'}."),
            "",
        ]
    io_utils.write_text(os.path.join(io_utils.OUTPUTS_DIR, "per_metric_results.md"), "\n".join(md))

    # Markdown: selection summary.
    sel = ["# Selection summary",
           "",
           "Methods are selected on production-measurable signals only. RMSE vs truth "
           "is shown for validation, not selection.",
           "",
           "| metric | selected method | family | early->long R2 | early CI covers eventual | RMSE vs truth (validation) |",
           "|---|---|---|---|---|---|"]
    for metric_name, mcfg in metrics.items():
        w = winners[metric_name]
        sel.append(
            f"| {mcfg['label']} | `{w['method']}` | {fam.get(w['method'],'')} | "
            f"{_fmt(w['pred_r2'],3)} | {_fmt(w['early_cover_long'],3)} | {_fmt(w['rmse_truth'])} |")
    sel += ["",
            "The winner differs across metrics by design and by result. See "
            "per_metric_results.md for the full tables and decision_impact.md for "
            "the decision-quality translation."]
    io_utils.write_text(os.path.join(io_utils.OUTPUTS_DIR, "selection_summary.md"), "\n".join(sel))

    # Markdown: decision impact.
    pm = impact["per_metric"]
    di = ["# Decision quality and illustrative business impact",
          "",
          "Better outlier handling produces better ship / no-ship decisions. The "
          "table compares each metric's selected method to the no-handling baseline.",
          "",
          "| metric | winner | decision error (none) | decision error (winner) | reduction (pp) | false-ship (none) | false-ship (winner) |",
          "|---|---|---|---|---|---|---|"]
    for metric_name, mcfg in metrics.items():
        p = pm[metric_name]
        di.append(
            f"| {mcfg['label']} | `{p['winning_method']}` | "
            f"{_fmt(p['decision_error_rate_none'],3)} | {_fmt(p['decision_error_rate_winner'],3)} | "
            f"{_fmt(p['decision_error_reduction_pp'],1)} | {_fmt(p['false_ship_rate_none'],3)} | "
            f"{_fmt(p['false_ship_rate_winner'],3)} |")
    tot = impact["program_totals"]
    di += [
        "",
        f"Mean decision-error reduction across metrics: "
        f"{_fmt(tot['mean_decision_error_reduction_pp'],1)} percentage points.",
        "",
        "## Confusion matrix per selected method",
        "",
        "Ship decision versus the ground-truth-correct action (positive = a real win "
        "that should ship), for the selected method against no handling. Precision is "
        "TP / (TP + FP), recall is TP / (TP + FN).",
        "",
        "| metric | method | true wins shipped (TP) | false ships (FP) | missed wins (FN) | correct holds (TN) | precision | recall |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for metric_name, mcfg in metrics.items():
        p = pm[metric_name]
        for label, key in [(p["winning_method"], "confusion_winner"), ("none", "confusion_none")]:
            c = p[key]
            prec = c["tp"] / (c["tp"] + c["fp"]) if (c["tp"] + c["fp"]) else 0.0
            rec = c["tp"] / (c["tp"] + c["fn"]) if (c["tp"] + c["fn"]) else 0.0
            di.append(
                f"| {mcfg['label']} | `{label}` | {c['tp']} | {c['fp']} | {c['fn']} | "
                f"{c['tn']} | {_fmt(prec,2)} | {_fmt(rec,2)} |")
    di += [
        "",
        "## Illustrative dollar translation",
        "",
        "This figure is illustrative and derived transparently from the stated "
        "assumptions below. It is not a real financial result.",
        "",
        f"- Revenue at stake per experiment decision: "
        f"${impact['assumptions']['revenue_at_stake_per_experiment_usd']:,}",
        f"- Experiments per year (program scale): {impact['assumptions']['experiments_per_year']}",
        f"- Illustrative annual loss avoided by using the per-metric winners instead "
        f"of no handling: ${tot['illustrative_total_annual_usd_avoided']:,.0f}",
        "",
        impact["assumptions"]["note"],
    ]
    io_utils.write_text(os.path.join(io_utils.OUTPUTS_DIR, "decision_impact.md"), "\n".join(di))

    write_explorer(config, summary, winners, impact, dec)

    return {
        "framework_results.json": os.path.join(io_utils.OUTPUTS_DIR, "framework_results.json"),
        "per_metric_results.md": os.path.join(io_utils.OUTPUTS_DIR, "per_metric_results.md"),
        "selection_summary.md": os.path.join(io_utils.OUTPUTS_DIR, "selection_summary.md"),
        "decision_impact.md": os.path.join(io_utils.OUTPUTS_DIR, "decision_impact.md"),
        "decision_impact.json": os.path.join(io_utils.OUTPUTS_DIR, "decision_impact.json"),
        "index.html": os.path.join(io_utils.ROOT, "docs", "index.html"),
    }


def write_explorer(config, summary, winners, impact, dec):
    """Self-contained per-metric method-comparison explorer (docs/index.html).

    Data is embedded inline so the page works when opened directly via file://.
    """
    order = [m["name"] for m in config["methods"]]
    fam = _family_map(config)
    metrics = config["metrics"]
    fig_index = {name: i for i, name in enumerate(metrics.keys(), start=1)}
    # Ground-truth ship-decision confusion counts per (metric, method).
    didx = dec.set_index(["metric", "method"])

    payload = {
        "metrics": {},
        "calibration_gate": config["scoring"]["calibration_gate"],
    }
    for metric_name, mcfg in metrics.items():
        g = summary[summary["metric"] == metric_name].set_index("method").reindex(order)
        rows = []
        for meth in order:
            r = g.loc[meth]
            dc = didx.loc[(metric_name, meth)]
            tp, fp, fn, tn = int(dc["tp"]), int(dc["fp"]), int(dc["fn"]), int(dc["tn"])
            rows.append({
                "method": meth,
                "family": fam.get(meth, ""),
                "bias": float(r["bias"]),
                "rmse_truth": float(r["rmse_truth"]),
                "variance": float(r["variance"]),
                "ci_coverage": float(r["ci_coverage"]),
                "early_cover_long": float(r["early_cover_long"]),
                "eligible": bool(r["eligible"]),
                "pred_r2": float(r["pred_r2"]),
                "pred_rmse": float(r["pred_rmse"]),
                "composite": float(r["composite_score"]),
                "tp": tp, "fp": fp, "fn": fn, "tn": tn,
            })
        payload["metrics"][metric_name] = {
            "label": mcfg["label"],
            "story": mcfg["outlier_story"],
            "winner": winners[metric_name]["method"],
            "comparison_image": f"images/m{fig_index[metric_name]}_{metric_name}_comparison.png",
            "rows": rows,
        }

    data_json = json.dumps(payload)
    html = _EXPLORER_TEMPLATE.replace("__DATA__", data_json)
    os.makedirs(os.path.join(io_utils.ROOT, "docs"), exist_ok=True)
    io_utils.write_text(os.path.join(io_utils.ROOT, "docs", "index.html"), html)


_EXPLORER_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Outlier-handling method explorer</title>
<style>
  :root { --ink:#1f2933; --muted:#7b8794; --grid:#e4e7eb; --win:#2f7d5b; --bad:#b23a48; --bg:#f7f8fa; }
  * { box-sizing: border-box; }
  body { margin:0; font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
         color:var(--ink); background:var(--bg); line-height:1.5; }
  header { padding:28px 32px 12px; }
  h1 { font-size:22px; margin:0 0 4px; }
  p.note { color:var(--muted); margin:4px 0; max-width:900px; }
  blockquote.disclaimer { margin:12px 0; padding:10px 16px; max-width:900px;
    background:#e8f3ee; border-left:4px solid var(--win); border-radius:8px; }
  main { padding:8px 32px 48px; }
  .controls { margin:18px 0; }
  select { font-size:15px; padding:8px 12px; border:1px solid var(--muted); border-radius:8px; background:white; }
  .story { max-width:900px; background:white; border:1px solid var(--grid); border-radius:10px;
           padding:14px 16px; margin:14px 0; }
  .winner { font-weight:600; color:var(--win); }
  img { max-width:100%; border:1px solid var(--grid); border-radius:10px; background:white; margin:10px 0; }
  table { border-collapse:collapse; width:100%; background:white; font-size:14px;
          border:1px solid var(--grid); border-radius:10px; overflow:hidden; }
  th, td { padding:8px 10px; text-align:right; border-bottom:1px solid var(--grid); }
  th:first-child, td:first-child { text-align:left; }
  th { background:#eef1f4; font-weight:600; }
  tr.win td { background:#e8f3ee; }
  tr.disq td { color:var(--bad); }
  tr.disq td:first-child::after { content:" (disqualified)"; font-size:12px; }
  .tag { display:inline-block; font-size:11px; padding:2px 8px; border-radius:999px; }
  .tag.win { background:var(--win); color:white; }
  footer { padding:0 32px 40px; color:var(--muted); font-size:13px; max-width:900px; }
</style>
</head>
<body>
<header>
  <h1>Per-metric outlier-handling method explorer</h1>
  <blockquote class="disclaimer"><strong>This is a portfolio demonstration built on synthetic data.</strong></blockquote>
  <p class="note">Pick a metric to see its outlier story,
  the full method comparison, and which method the framework selects. Selection
  uses only production-measurable signals: predictiveness (does the early reading
  track the eventual long-term reading) and a calibration gate. A method is
  disqualified when its early 95 percent CI fails, too often, to cover the
  eventual long-term estimate, a sign it is over-confident. The last columns are
  ground-truth checks, shown only to validate the choice, never to make it: RMSE vs
  truth, and the ship-decision confusion counts (wins shipped, false ships, missed
  wins, correct holds) for every method.</p>
</header>
<main>
  <div class="controls">
    <label for="metric">Metric: </label>
    <select id="metric"></select>
  </div>
  <div class="story" id="story"></div>
  <img id="fig" alt="method comparison figure">
  <table id="tbl">
    <thead><tr>
      <th>method</th><th>family</th><th>early to long R2</th>
      <th>early CI covers eventual</th><th>predictiveness</th>
      <th>RMSE vs truth (val.)</th>
      <th>wins shipped (TP)</th><th>false ships (FP)</th><th>missed wins (FN)</th><th>correct holds (TN)</th>
    </tr></thead>
    <tbody></tbody>
  </table>
</main>
<footer>Generated by scripts/run_demo.py from a fixed seed. All numbers are from
the actual run.</footer>
<script>
const DATA = __DATA__;
const sel = document.getElementById('metric');
Object.keys(DATA.metrics).forEach(k => {
  const o = document.createElement('option');
  o.value = k; o.textContent = DATA.metrics[k].label; sel.appendChild(o);
});
function fmt(x, p){ return Number(x).toFixed(p); }
function render(key){
  const m = DATA.metrics[key];
  document.getElementById('story').innerHTML =
    '<p><span class="tag win">winner: ' + m.winner + '</span></p><p>' + m.story + '</p>';
  document.getElementById('fig').src = m.comparison_image;
  const tb = document.querySelector('#tbl tbody');
  tb.innerHTML = '';
  m.rows.forEach(r => {
    const tr = document.createElement('tr');
    if (r.method === m.winner) tr.className = 'win';
    else if (!r.eligible) tr.className = 'disq';
    tr.innerHTML =
      '<td>' + r.method + '</td>' +
      '<td>' + r.family + '</td>' +
      '<td>' + fmt(r.pred_r2,3) + '</td>' +
      '<td>' + fmt(r.early_cover_long,3) + '</td>' +
      '<td>' + fmt(r.composite,3) + '</td>' +
      '<td>' + fmt(r.rmse_truth,4) + '</td>' +
      '<td>' + r.tp + '</td>' +
      '<td>' + r.fp + '</td>' +
      '<td>' + r.fn + '</td>' +
      '<td>' + r.tn + '</td>';
    tb.appendChild(tr);
  });
}
sel.addEventListener('change', e => render(e.target.value));
render(sel.value);
</script>
</body>
</html>
"""
